### ISSUE TITLE
Revert window after clicking link?

### ISSUE THREAD

**Issue by zeke** [zeit/hyperlinks#9] opened 2016-08-29 04:06 UTC
The link worked, but my window has been overtaken by clicking on it. Is there a way to return to the window state before I clicked the link? `^ C` doesn't seem to work for me.

![screen shot 2016-08-28 at 9 04 07 pm](https://cloud.githubusercontent.com/assets/2289/18040479/1a1e3f7a-6d63-11e6-887e-9e42f8bdeba3.png)

**Comment by nkzawa** [comment] 2016-08-29 10:09
duplicate of https://github.com/zeit/hyperlinks/issues/2
focus on the HyperTerm window before `Ctrl+C`.

**Closed by nkzawa** 2016-08-29 10:09 UTC
